# Generated by Django 5.0.6 on 2024-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_enable', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
